### PR TITLE
Added a comment that require IAM configuration to Azure Blob Storage

### PR DESCRIPTION
**Pull request by hiroakit**
This is a feedback.

**Reason:**

I tried to run the ShowCase unity project in Unity while reading the following documents:

1. https://docs.microsoft.com/en-us/azure/remote-rendering/samples/showcase-app
2. https://docs.microsoft.com/en-us/azure/remote-rendering/quickstarts/convert-model

However, I didn't realize that IAM settings required in Azure Storage, and several hours passed...
On the other hand, searching carefully in docs.microsoft.com, we will find the corresponding description page:

- https://docs.microsoft.com/en-us/azure/remote-rendering/how-tos/create-an-account#link-storage-accounts

Therefore, I thought it would make the introduction smoother and save time to have the URL around RemoteObject.cs L: 691.

### CODE REVIEW

**Review by FlorianBorn71 — COMMENTED** [review]
Thanks for this PR. We think additional info propagated to the user is indeed useful here, but we'll discuss internally whether this should mention Blob Storage specifically, since there may be more storage options in the future. I'll keep you updated here.

**Comment by FlorianBorn71** [comment]
Hi, quick update here:
To be less specific about the storage type, we decided to do the following:
- add a new troubleshooting item, specifically for 'failed to load model': https://docs.microsoft.com/en-us/azure/remote-rendering/resources/troubleshoot#failed-to-load-model
- in the tool error output, link to that entry

That way we have an extra indirection that allows us to add more troubleshooting guides in the future to the docs.

**Comment by FlorianBorn71** [comment]
That said, you can abandon this PR, because our change will be deployed to this repo with the next release.
Thanks for all your contributions, it's always very welcome!

**Comment by hiroakit** [comment]
Hi, Florian. 
Thank you for your kind reply.
The [plan](https://github.com/Azure/azure-remote-rendering/pull/39#issuecomment-877334356) is so cool, then I closed this PR.

**Pull request closed without merging**
